pipeline {
    agent any
    tools { 
        maven 'Maven3' 
        
    }
    stages {
        stage('Build') {
            steps {
                
                bat 'mvn -B -DskipTests clean package'
                
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                    
                    emailtext(
                    subject: "it is a mail for junit tests"
                    body:"check the result: <a href="${env.BUILD_URL}">"
                    to: "sudhakar.pro00@gmail.com"
                    from: "sudhakar.srivastava84@gmail.com"
                    )
                }
            }
        }
        /*stage('Deliver') {
            steps {
                bat './jenkins/scripts/deliver.sh'
            }
        }*/
    }
}
